### ISSUE TITLE
Esquelete e estructuración do xogo

### ISSUE THREAD

**Issue by DavidVidaMi** [DavidVidaMi/Sadhana#2]
## Estructura de clases

Crear e organizar as distintas clases que se utilizarán no proxecto. 
Exemplo: GameManager, InxtrumentoX, InstrumentoY...

**Comment by Gontrojon** [comment]
Me pongo con esto ahora, lo subiré en la rama feature/EstructuraBasica

**Comment by Gontrojon** [comment]
Me llevo aprox 25-30 minutos el plantear y hacer la estructura.
