### ISSUE TITLE
Botón de Compra del Saxofón no funciona 

### ISSUE THREAD

**Issue by AdrianNYV** [DavidVidaMi/Sadhana#21]
**Problema**: 
Al abrir el menú de compra y mostrar todos los botones de compra de Instrumentos todos funcionan correctamente menos 1, el del Saxofón.

**Solución**: 
Parece ser que no está colocada su función correctamente en el propio botón del _Safoxón_, faltando una referencia en el _**OnClick()**_ para que llame a un método para poder hacer la compra, se soluciona fácilmente llamando a la función correcta en el _**OnClick()**_.

**Comment by Gontrojon** [comment]
Me pongo con esto, y lo arreglo en un momento lo subiré a una rama bugfix/CompraSaxofon

**Comment by Gontrojon** [comment]
Arreglado,  a la espera del merge para cerrar isue.

**Comment by DavidVidaMi** [comment]
Si podes poñer o tempo aprox que che levou agradesido.

**Comment by Gontrojon** [comment]
Me levo aprox unos 10 minutos
