### ISSUE TITLE
Consola llena de Puntuación...

### ISSUE THREAD

**Issue by AdrianNYV** [DavidVidaMi/Sadhana#22]
La consola imprime cada muy poco la puntuación que se genera, no dejando ver bien otras impresiones de consola como la detección de botones o el click de compra.

**Posible solución**: 
Darle un tiempo para que imprima el comentario de puntuación, por ejemplo que lo imprima cada 5 segundos, para dar tiempo a ver otros _Debug.Log/print_ con mayor facilidad. 

O ya se imprime perfectamente en pantalla, así que se podría eliminar ya sin problemas, pero preferiblemente con darle un tiempo por si se quiere seguir probando más implementaciones en código referentes a la puntuación y ver que todo esté correcto.

**Comment by Gontrojon** [comment]
Se dejaría algún log o print de las primeras implementaciones, ahora lo reviso.

**Comment by DavidVidaMi** [comment]
Fantástico, dudo que levase moito tempo ao ser algo tan trivial así que contaremos o tempo desta tarefa como despreciable.
