### ISSUE TITLE
Texto de Notas (puntuación) muy pequeño

### ISSUE THREAD

**Issue by AdrianNYV** [DavidVidaMi/Sadhana#23]
En comparación con el resto de textos importantes y botones como el de _Pausa_ o el del _Menú de Compra_ el texto de la puntuación, las **_Notas_** es algo pequeño, estaría bien que fuera algo más grande para que se viera bien en pantalla.

**Comment by Gontrojon** [comment]
Ya lo he arreglado ahora debería poder leerse mejor

**Comment by DavidVidaMi** [comment]
Okey, si podes Trojan dime o que che levou esa tarefa e Adri se me podes comentar canto che levou o testeo en general sería maravilloso.

**Comment by Gontrojon** [comment]
aprox 10 minutos

**Comment by AdrianNYV** [comment]
Horas de Testeo del Sábado: 4h 30min aprox.
Horas de Testeo del Domingo por la mañana: 2h 30min.
