### ISSUE TITLE
Pantalla principal

### ISSUE THREAD

**Issue by DavidVidaMi** [DavidVidaMi/Sadhana#4]
## Pantalla principal e bucle de xogo:

Esta tarea consistirá na creación da pantalla principal na que se desenvolverá o xogo xunto coa detección de click que terá que facer un ruido de palmas e sumar +1 á puntuación.

**Comment by Gontrojon** [comment]
Me pongo con esto ahora, lo subiré en la rama feature/PantallaPrincipal.

**Comment by Gontrojon** [comment]
Estada creada la pullrequest, me llevo aprox 15-20 mnt
