### ISSUE TITLE
Instrumentos básicos pantalla 1

### ISSUE THREAD

**Issue by DavidVidaMi** [DavidVidaMi/Sadhana#5]
## Facer prefabs dos distintos instrumentos:

Esta tarea consistirá en crear os prefabs dos distintos instrumentos, deben estar listos para cando se poñan na pantalla principal sone o sonido correspondente e sumen +X puntuación cada segundo.

**Comment by Victordf2005** [comment]
27/03/2023. Tiempo dedicado: 0:50 
28/03/2023. Tiempo dedicado: 0:45
