### ISSUE TITLE
Refactorizar clase Instrumento

### ISSUE THREAD

**Issue by DavidVidaMi** [DavidVidaMi/Sadhana#8]
Facer que a clase instrumento teña obligatoriamente un audiosource que esté sonando en todo momento en bucle (co sonido a 0 hasta que se desbloquee o instrumento). Incluir no Update() que cada segundo que pase sume X cantidade de puntos. Cambiar o nombre das variables a corde cos cambios a facer.

**Comment by Gontrojon** [comment]
Me pongo con esto ahora, lo subiré en la rama refactor/Instrumento.

**Comment by Gontrojon** [comment]
Creada pullrequest tiempo empleado poco más de 1 hora
